### PR TITLE
use Ember.get for property lookup

### PR DESCRIPTION
**Pull request by ssured**
This allows for dependent properties

### CODE REVIEW

**Comment by miguelcobain** [comment]
Do you mind to explain this a little better? What's the use case this solves?

Does this mean that you can assign the `create` value to a variable in the template?

**Comment by ssured** [comment]
I am embedding Ember-Selectize into https://github.com/ember-addons/ember-forms using the attached code. As you can see I alias properties to a higher scope. Higher scope settings changes will trickle down into the ember-selectize view.

In general it is advised to always use ember observable properties in bindings, it's computationally very cheap and will not surprise your users.

``` coffeescript
EmSelectizeComponent = Ember.Forms.FormSelectComponent.extend
  controlView: Ember.Selectize.extend Ember.Forms.ControlMixin,
    id:              Ember.computed -> 'id' + Math.random().toString(36).substr(2)
    plugins:         ["remove_button", "restore_on_backspace"]

    content:         Ember.computed.alias 'parentView.content'
    optionValuePath: Ember.computed.alias 'parentView.optionValuePath'
    optionLabelPath: Ember.computed.alias 'parentView.optionLabelPath'
    selection:       Ember.computed.alias 'parentView.selected'
    placeholder:     Ember.computed.alias 'parentView.prompt'

    multiple:        Ember.computed.alias 'parentView.multiple'
    create:          Ember.computed.alias 'parentView.create'

  #Property
  property: undefined

  # selected is an inderect reference to model.property
  # thanks to http://alexspeller.com/simple-forms-with-ember/
  selected: undefined
  _tearDownBindings: (->
    @_selectedBinding?.disconnect @ # disconnect old binding if it exists
    @_selectedBinding = null
  ).on 'willDestroyElement'
  _setupSelectedBindings: Ember.observer('propertyName', 'model', ->
    @_tearDownBindings()
    @_selectedBinding = Ember.Binding.from("model.#{@get 'propertyName'}").to('selected')
    @_selectedBinding.connect @
  ).on 'init'

  content: undefined
  optionValuePath: undefined
  optionLabelPath: undefined
  prompt: undefined

  multiple: false
  create: false

  actions:
    create: (value) ->
      @get('content').pushObject value
      if @get 'multiple'
        unless Ember.isArray selected = @get 'selected'
          @set 'selected', selected = Ember.A []
        selected.pushObject value
      else
        @set "selected", value

`export default EmSelectizeComponent`
```

**Comment by miguelcobain** [comment]
Makes perfect sense.

Merging and closing. Thanks!

**Comment by ssured** [comment]
Thanks to you in the first place for this nice connection between Selectize and Ember!

**Pull request merged**
