### PR TITLE
Component

### PR DESCRIPTION
**Pull request by knownasilya**
**This is a WIP, please don't merge yet.**

Currently three tests fail, mainly handling `null` content. Would love input.

Failing tests:
screen shot 2014-07-28 at 2 09 47 pm

### CODE REVIEW

**Comment by miguelcobain** [comment]
Probably not related to the failing tests, but did you pull in the latest changes from master?

https://help.github.com/articles/syncing-a-fork

**Comment by knownasilya** [comment]
@miguelcobain yup, all synced.

**Comment by miguelcobain** [comment]
I believe that the test `should be able to select an option and then reselect the prompt` isn't valid in ember-selectize.

`Ember.Select` handles the prompt as a regular selectable option. In selectize the prompt is handled separately using the `placeholder` attribute.
As I mentioned in the readme, the tests were borrowed from `Ember.Select` and many of them were left untouched. That's why they fail. Many of them aren't even valid in the ember-selectize context. Other don't fail, but are still using Ember.Select, I think.

Keep in mind that:
- `Ember.Select` tests handle the DOM <-> Ember
- Selectize's tests handle selectize <-> DOM
- ember-selectize resides between Ember and Selectize (making the overall picture like: _Ember <-> ember-selectize <-> Selectize <-> DOM_), so **the tests should focus on the synchronization between Ember and Selectize**. We shouldn't test that the DOM is being updated correctly, because that is assured by Selectize's own tests. We should just test that the options selectize recognizes are the same as our array bindings, etc.

A useful test to replace the "prompt" one mentioned above would be to make sure that selectize recognized the placeholder upon creation, because that is ember-selectize's responsibility.

**Comment by knownasilya** [comment]
@miguelcobain thanks for clearing that up. This was an old PR I started a while back, so I forgot that not all tests are relevant.

**Pull request closed without merging**
